### ISSUE TITLE
ExpressJS Async / Await wrapper not working

### ISSUE THREAD

**Issue by ekoome** [wavded/www#1]
Hi Marc 

I enjoyed your article on asynchronous error handling in express especially with es7.

I have migrated my callbacks to promises & async / await construct using typescript 2.1. However, when employing your technique to wrap handlers with async / catch, any thrown errors within the handler result in unhandledpromiseexception rather than being caught and sent to the error handler.

What am I doing wrong.

let wrap = fn => (...args) => fn(...args).catch(args[2])

public static create {

route.post("/api/auth", wrap ( async (req, res, next) => {
new userRoute.authenticate();
}));
}

public async authenticate {

...

If (authfails) 
// this results in unhandled promise error
 throw AuthenticationError("Auth failed");

...

}

Let me know where am getting this wrong.

**Comment by wavded** [comment]
@ekoome I believe we solved this over email but if I have the wrong person, let me know!
